root: true
extends:
  - eslint-config-cheminfo
  - plugin:flowtype/recommended
env:
  jest: true
parserOptions:
  sourceType: module
parser: babel-eslint
plugins:
  - flowtype
rules:
  flowtype/no-weak-types:
    - error
    - Object: false
