language: node_js
node_js:
  - node
before_script: yarn run bootstrap
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
env:
  - CXX=g++-4.9
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    on_success: change
    on_failure: change
